name: ussd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.2+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phone_direct_caller:
    git:
      url: https://github.com/YoussefLasheen/flutter-phone-direct-caller.git
      ref: 3dafeee
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.2.3 

flutter:
  uses-material-design: true

flavorizr:
  ide: vscode
  flavors:
    vodafone:
      app:
        name: "Vodafone Codes"
        icon: "app_icons/vodafone.png"
      android:
        applicationId: "dev.lasheen.ussd.vodafone"

    orange:
      app:
        name: "Orange Codes"
        icon: "app_icons/orange.png"
      android:
        applicationId: "dev.lasheen.ussd.orange"

    we:
      app:
        name: "We Codes"
        icon: "app_icons/we.png"
      android:
        applicationId: "dev.lasheen.ussd.we"

    etisalat:
      app:
        name: "Etisalat Codes"
        icon: "app_icons/etisalat.png"
      android:
        applicationId: "dev.lasheen.ussd.etisalat"
